trigger:
- main

pool:
  vmImage: ubuntu-latest

  variables:
    ServiceConnectionName: 'serviceconnection-iac-devops-test'
    EnvironmentType: 'Test'
    ResourceGroupName: 'testRG'

  stages:
    - stage: Deploy
  jobs:
    - job:      
      steps:      
      - task: AzureCLI@2
        inputs:
          azureSubscription: serviceconnection-iac-devops-test
          resourceGroupName: 'testrg'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create \
              --name $(Build.BuildNumber) \
              --resource-group testrg \
              --template-file Bicep/learn/Level1/main.bicep \
            
