trigger:
- main

pool:
  vmImage: ubuntu-latest
  jobs:
    - job:
      steps:      
      - task: AzureCLI@2
        inputs:
          azureSubscription: serviceconnection-iac-devops-test
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create \
              --name $(Build.BuildNumber) \
              --resource-group testrg \
              --template-file Bicep/learn/Level1/main.bicep \
